### ISSUE TITLE
demo中的StickWidget可点击，拷贝到自己的flutter工程中，无法点击

### ISSUE THREAD

**Issue by songdongliang** [CarGuo/gsy_flutter_demo#15]
郁闷，不知道什么情况；是跟本地什么版本有关系吗

**Comment by CarGuo** [comment]
我记得好像遇到过这个问题，但是修复过好像····具体什么问题我还真忘记了·····

**Comment by songdongliang** [comment]
environment:
  sdk: ">=2.4.9 <3.0.0"
这里改为一致即可，flutter clean后如果不行，清楚缓存重启studio
