### ISSUE TITLE
绘制气泡代码逻辑

### ISSUE THREAD

**Issue by PhoenixLeeSin** [CarGuo/gsy_flutter_demo#17]
代码位置：bubble文件夹 bubble_painter.dart
///绘制左边三角形
`
原代码
    if (mArrowCenter) {
      mArrowPosition = (rect.bottom - rect.top) / 2 - mArrowWidth / 2;
    }
应改为
    if (mArrowCenter) {
      mArrowPosition = (rect.bottom - rect.top) / 2 - mArrowHeight / 2;
    }
`
大佬看一下对吗

**Comment by CarGuo** [comment]
you are right ，thx 。

马上改
