### ISSUE TITLE
时钟动画

### ISSUE THREAD

**Issue by PhoenixLeeSin** [CarGuo/gsy_flutter_demo#19]
void drawHourCircle 绘制小时时， 判断当前时间并修改其颜色应为
`
    for (var i = 0; i < 12; i++) {
      canvas.save();
      double iDeg = 2 * math.pi / 12 * i; //时间为24小时制
      canvas.rotate(iDeg);
      bool colorTime = (iDeg / (2 * math.pi) * 360).floor().abs() ==
          (degree / (2 * math.pi) * 360).floor().abs();
      Color color = colorTime ? Colors.blueAccent : Colors.white;
      drawText(canvas, "${(i + 1).toString()}点", color, hourRadius, Offset.zero,
          textAlign: TextAlign.right, fontSize: fontSize);
      canvas.restore();
    }
`

**Comment by CarGuo** [comment]
？？什么问题？

**Comment by PhoenixLeeSin** [comment]
源代码判断的不对 导致 当前的小时颜色无变化
