### ISSUE TITLE
我想问一下flutter web支持微前端框架吗

### ISSUE THREAD

**Issue by guchengxi1994** [CarGuo/gsy_flutter_demo#24]
如题，我本身觉得js的前端框架体系太多太乱，所以一直提不起兴趣，现在团队想搞Qiankun的微前端框架，我想问一下可以把flutter  web嵌入这个框架内吗？我在Qiankun项目的issue里看到有人问这个问题，回答的是如果用canvas渲染的是不行的，但是没说用html渲染的情况，所以想咨询一下

**Comment by CarGuo** [comment]
没用过 Qiankun ···· 理论上我理解····也只能 iframe

**Comment by guchengxi1994** [comment]
好的谢谢
