### ISSUE TITLE
stick

### ISSUE THREAD

**Issue by sunzhongliangde** [CarGuo/gsy_flutter_demo#35]
'package:flutter/src/rendering/box.dart': Failed assertion: line 2178 pos 16: 'sizeAccessAllowed': RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout() in RenderTransform.performLayout.

使用flutter新建了一个项目，直接copy stick组件到项目当中，运行起来就报这样的警告导致stick组件没有吸顶效果.
flutter 环境
`[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
    • Flutter version 3.24.0 on channel stable at C:\Users\sun\flutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 months ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\sun\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: D:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.8.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.8.34511.84
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2024.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\sun\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (4 available)
    • sdk gphone16k x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)             • windows       • windows-x64    • Microsoft Windows [版本 10.0.22631.4317]
    • Chrome (web)                  • chrome        • web-javascript • Google Chrome 129.0.6668.101
    • Edge (web)                    • edge          • web-javascript • Microsoft Edge 120.0.2210.144

[!] Network resources
    X A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到

! Doctor found issues in 2 categories.`

**Comment by CarGuo** [comment]
size 问题，需要确定一个 parent size 的方式我猜
